services:
  database:
    image: postgres:15
    env_file:
      - ./env/database.env
    volumes:
      - database_data:/var/lib/postgresql/data
  backend:
    depends_on:
      - database
    build:
      context: .
      dockerfile: ./docker/Dockerfile.local
    ports:
      - "8080:8080"
    env_file:
      - ./env/backend.env
    volumes:
      - .:/develop

volumes:
  database_data: {}
