services:
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.production
    ports:
      - "8080:8080"
    env_file:
      - ./env/production/backend.env

volumes:
  database_data: {}
